/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyLib_mylib */

#ifndef _Included_MyLib_mylib
#define _Included_MyLib_mylib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyLib_mylib
 * Method:    print
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_MyLib_mylib_print
  (JNIEnv *, jobject, jstring);

/*
 * Class:     MyLib_mylib
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_MyLib_mylib_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
